# -*- coding: utf-8 -*-
"""automate_DataSekolah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJGppDdUm7-npOgcX6gS6O4-OO8bNPzR
"""

!pip install kaggle pandas

!pip install feature-engine

import pandas as pd
import os
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from feature_engine.outliers import Winsorizer
from sklearn.compose import ColumnTransformer

# Mengunduh dataset dari kaggle
dataset_path = kagglehub.dataset_download('puanbeningpastika/dataset-pendidikan-sd-indonesia-2023-2024')
print("Dataset berhasil diunduh di folder:", dataset_path)

files = os.listdir(dataset_path)
file_path = os.path.join(dataset_path, files[0])

df = pd.read_csv(file_path)
# Drop the 'Unnamed: 14' column as it appears to contain only NaN values
if 'Unnamed: 14' in df.columns:
    df = df.drop(columns=['Unnamed: 14'])

csv_output_path = 'Data-Sekolah.csv'
df.to_csv(csv_output_path, index=False)
print("CSV berhasil disimpan di:", csv_output_path)

df = df.dropna()

def preprocess_data(df):
    df = df.drop_duplicates()
    return df

# Define 'cols' with the numerical columns to be scaled.
# It is crucial to ensure that the DataFrame 'df' is not empty before this step.
# The 'Unnamed: 14' column should ideally be dropped earlier if it causes df to become empty.

# Select all numerical columns, excluding 'Provinsi' as it's categorical.
# If 'Unnamed: 14' was not dropped, it might be included here but will be handled if df is empty.
# Assuming 'Provinsi' is of object/string type and other relevant columns are numerical.
numerical_cols_to_scale = df.select_dtypes(include=['number']).columns.tolist()

# Ensure 'Provinsi' is not in the list if it accidentally was, or if its type changed.
if 'Siswa' in numerical_cols_to_scale:
    numerical_cols_to_scale.remove('Siswa')

cols = numerical_cols_to_scale

# Proceed with scaling only if the DataFrame is not empty and there are columns to scale
if not df.empty and cols:
    scaler = MinMaxScaler()
    df[cols] = scaler.fit_transform(df[cols])
    print("Selected numerical columns have been scaled using MinMaxScaler.")
elif df.empty:
    print("Error: The DataFrame is empty. Please ensure 'Unnamed: 14' is dropped and df.dropna() doesn't remove all rows before this step.")
else:
    print("No numerical columns found to scale.")

winsor = Winsorizer(
    capping_method='iqr',
    tail='both',
    fold=1.5,
    # The column 'Pendapatan' does not exist in the dataframe.
    # Please replace with a valid numerical column you wish to cap for outliers.
    # For example, variables=['Siswa'] or variables=['Mengulang']
    # variables=['Pendapatan']
)

# df = winsor.fit_transform(df)

df_encoded = pd.get_dummies(
    df,
    columns=['Provinsi'],
    drop_first=True
)

def preprocess_data(df):

    num_cols = df.select_dtypes(include=['int64', 'float64']).columns
    cat_cols = df.select_dtypes(include=['object', 'category']).columns

    preprocessor = ColumnTransformer([
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(drop='first'), cat_cols)
    ])

    X = preprocessor.fit_transform(df)

    return X

def preprocess_data(df, target_col):
    """
    Melakukan preprocessing:
    - Pisahkan fitur dan target
    - Handle missing values
    - One-hot encoding untuk kolom kategorikal
    - Return X_processed, y
    """

    X = df.drop(columns=[target_col])
    y = df[target_col]

    categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
    numerical_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

    # Handle missing values
    X[categorical_cols] = X[categorical_cols].fillna("Unknown")
    X[numerical_cols] = X[numerical_cols].fillna(0)

    # One-hot encoding
    encoder = OneHotEncoder(handle_unknown="ignore", sparse=False)
    X_cat_encoded = encoder.fit_transform(X[categorical_cols])

    # Gabungkan data
    X_processed = pd.concat(
        [
            pd.DataFrame(
                X_cat_encoded,
                columns=encoder.get_feature_names_out(categorical_cols)
            ),
            X[numerical_cols].reset_index(drop=True),
        ],
        axis=1
    )

    return X_processed, y, encoder

print("Preprocessing selesai.")